project:
  type: website

website:
  title: Pattern Pioneers
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-523-Exercises/project-final-Pattern-Pioneers
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd
    logo: images\pp_logo.png
  favicon:  images\pp_logo.png

format:
  html:
    theme: Minty
    toc: true

execute:
  freeze: auto
